// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX0Sbl_F6UACDKrE7aHGTIPlgoa-d3O1c',
    appId: '1:257580144907:web:3774223f65c09135b32a0e',
    messagingSenderId: '257580144907',
    projectId: 'app-lista-tarefas-fatec-338b6',
    authDomain: 'app-lista-tarefas-fatec-338b6.firebaseapp.com',
    storageBucket: 'app-lista-tarefas-fatec-338b6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEGQcogDuBamQHg_XoB5nhweFlJoLCo3w',
    appId: '1:257580144907:android:2f80509932cc6266b32a0e',
    messagingSenderId: '257580144907',
    projectId: 'app-lista-tarefas-fatec-338b6',
    storageBucket: 'app-lista-tarefas-fatec-338b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDraLX1CCn7kTO4EWY-mVbZpfypBdbwyE',
    appId: '1:257580144907:ios:391e9a32320721f3b32a0e',
    messagingSenderId: '257580144907',
    projectId: 'app-lista-tarefas-fatec-338b6',
    storageBucket: 'app-lista-tarefas-fatec-338b6.appspot.com',
    iosBundleId: 'com.example.app07Firebase',
  );
}
