// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgXlzn9vEx0Lht3k4IXqX43O1apsOnGU0',
    appId: '1:701964141696:web:217cd4008d0de86a8d9265',
    messagingSenderId: '701964141696',
    projectId: 'fatec-loja-cafe-noite-2022',
    authDomain: 'fatec-loja-cafe-noite-2022.firebaseapp.com',
    storageBucket: 'fatec-loja-cafe-noite-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWhE1Cmpdp1A2KzalO1BxaqQXC-UNrtFU',
    appId: '1:701964141696:android:5d2eff9b144f151d8d9265',
    messagingSenderId: '701964141696',
    projectId: 'fatec-loja-cafe-noite-2022',
    storageBucket: 'fatec-loja-cafe-noite-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYtkjXxOi20uWIcMm8K1SNjA0CC531Wno',
    appId: '1:701964141696:ios:172259eb8fd768b98d9265',
    messagingSenderId: '701964141696',
    projectId: 'fatec-loja-cafe-noite-2022',
    storageBucket: 'fatec-loja-cafe-noite-2022.appspot.com',
    iosClientId: '701964141696-5hvooojriem9uqls4o88bsktmqkj8oa4.apps.googleusercontent.com',
    iosBundleId: 'com.example.app07CafeStore',
  );
}
